name: Static Code Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install PMD
        run: sudo apt-get update && sudo apt-get install -y pmd

      - name: Run PMD Analysis
        run: |
          pmd -d src -f text -R rulesets/java/basic.xml,rulesets/java/design.xml > pmd-report.txt

      - name: Display PMD report
        run: cat pmd-report.txt
