name: Static Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Checkstyle Analysis
        run: mvn checkstyle:check

      - name: Run PMD Analysis
        run: mvn pmd:check

      - name: Run SpotBugs Analysis
        run: mvn spotbugs:check

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Analysis-Reports
          path: target/site
