name: Static Code Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          sudo mv pmd-bin-6.55.0 /opt/pmd

      - name: Run PMD Analysis
        run: |
          /opt/pmd/bin/run.sh pmd -d src -f text -R /opt/pmd/lib/rulesets/java/basic.xml,/opt/pmd/lib/rulesets/java/design.xml > pmd-report.txt

      - name: Display PMD report
        run: cat pmd-report.txt
