name: Static Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Compile the project
        run: javac -d out $(find src -name "*.java")

      - name: Run Checkstyle Analysis
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.10.0/checkstyle-10.10.0-all.jar
          java -jar checkstyle-10.10.0-all.jar -c /google_checks.xml src/**/*.java

      - name: Run PMD Analysis
        run: |
          curl -LJO https://github.com/pmd/pmd/releases/download/pmd_releases/6.57.0/pmd-bin-6.57.0.zip
          unzip pmd-bin-6.57.0.zip
          ./pmd-bin-6.57.0/bin/run.sh pmd -d src/ -f text -R rulesets/java/quickstart.xml

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Analysis-Reports
          path: out/
